const ADD_RELATIVE_ALERT = "ADD_RELATIVE_ALERT";
const CLEAR_RELATIVE_ALERTS = "CLEAR_RELATIVE_ALERTS";
const SHOW_RELATIVE_ALERTS = "SHOW_RELATIVE_ALERTS";


export {ADD_RELATIVE_ALERT, CLEAR_RELATIVE_ALERTS, SHOW_RELATIVE_ALERTS};